//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jthacker2747ex3a1ef.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessEntity
    {
        public int BusinessEntityID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
